# Default values for api-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.cn-hangzhou.aliyuncs.com/hzero-hzero/hcbm-front-integration

# preJob:
#   preConfig:
#     mysql:
#       host: localhost
#       port: 3306
#       username: choerodon
#       password: 123456
#       dbname: iam_service

service:
  enable: false
  type: ClusterIP
  port: 80
  name: hcbm-front-integration

ingress:
  enable: false

env:
  open:
    BUILD_BASE_PATH: /
    BUILD_WEBSOCKET_HOST: ws://dev.hzero.org:8120
    BUILD_BPM_HOST: http://dev.hzero.org:8170
    BUILD_CLIENT_ID: hcbm-front-integration-uat
    BUILD_API_HOST: http://dev.hzero.org:8080/
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    BUILD_PLATFORM_VERSION: SAAS

logs:
  parser: nginx

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    # memory: 2Gi
  requests:
    # cpu: 100m
    # memory: 1Gi

